// All 13 mission definitions for the ClearBank AFASA Training Wizard
// Step types: 'trust' | 'input' | 'gate' | 'restart' | 'snippet' | 'upload'
// Gate steps auto-run on unlock, auto-retry 3x, then surface Retry button

export const MISSION_ORDER = ['M0','M1','M2','M3','M4','M5','M6','M7','M8','M9','M10','M11','M12'];

export const MISSIONS = {
  M0: {
    title: 'Pre-requisites',
    article: 'AFASA Onboarding',
    narrative: 'Configure your local environment and create your Descope project before the training begins.',
    steps: [
      {
        id: 'step1',
        type: 'input',
        title: 'Set your base email address',
        description: 'All actor accounts are derived from this using plus-addressing (e.g. +joel@, +alex@). Use a Gmail you control.',
        envKey: 'BASE_EMAIL',
        placeholder: 'yourname@gmail.com',
        label: 'Base Email',
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Create a Descope account',
        description: 'Go to descope.com, sign up free, and create a new project named "ClearBank".',
        buttonLabel: 'Account Created',
      },
      {
        id: 'step3',
        type: 'input',
        title: 'Save your Descope Project ID',
        description: 'In Descope → Project Settings, copy the Project ID (starts with "P") and paste it below. This activates the Descope authentication widget on the login page.',
        envKey: 'VITE_DESCOPE_PROJECT_ID',
        placeholder: 'P2abc...',
        label: 'Descope Project ID',
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Pre-requisites complete',
        description: 'Your environment is configured. Sarah Chen will issue Mission 1 directives shortly.',
        buttonLabel: 'Complete Pre-requisites',
      },
    ],
  },

  M1: {
    title: 'First Contact',
    article: 'AFASA Article 3',
    narrative: 'Import ClearBank\'s three legacy customer accounts into Descope to centralise identity management.',
    steps: [
      {
        id: 'step1',
        type: 'upload',
        title: 'Upload the trainer\'s legacy user CSV',
        description: 'The trainer provided a CSV file before the workshop with pre-set passwords for ClearBank\'s three legacy customer accounts. Upload it here — the server will hash the passwords and show you a preview before import.',
        buttonLabel: 'Confirmed',
      },
      {
        id: 'step2',
        type: 'input',
        title: 'Save your Management API Key',
        description: 'In Descope → Company Settings → Management Keys, create a key with full permissions. Paste it below — stored server-side only, never sent to the browser.',
        envKey: 'DESCOPE_MANAGEMENT_KEY',
        placeholder: 'K2_...',
        label: 'Management API Key',
        secret: true,
      },
      {
        id: 'step3',
        type: 'gate',
        title: 'Import Joel, Alex, and Vicky via Management API',
        description: 'Backend reads the trainer CSV and imports all three legacy accounts with passwords via the Descope Management API. Retry on failure — check your key has full user management permissions.',
        endpoint: '/api/verify/m1-import',
        getBody: () => ({}),
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Confirm all three accounts in Descope Console',
        description: 'Navigate to User Management in Descope Console and verify Joel, Alex, and Vicky appear as Enabled accounts.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M2: {
    title: 'New Customers',
    article: 'AFASA Article 4',
    narrative: 'Onboard three new customer accounts (Jane, Bill, Beth) into Descope per AFASA Article 4. They will be Active but have no credentials until M5.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Open the JSON Import tab in Descope Console',
        description: 'In Descope → User Management → Import, switch to the JSON tab. You will paste a user list here to batch-import new customers.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'snippet',
        title: 'Import new customers into Descope',
        description: 'In Descope Console → User Management → Import Users, click the JSON tab. Paste the JSON below into the text area, or download and upload the file. These accounts will appear as Active — the account record exists in Descope but they have zero credentials (no password, no passkey, no magic link). They cannot log in until M5 configures a passwordless flow for them. Click Import when done, then return here.',
        buttonLabel: 'Imported',
        downloadName: 'new-customers.json',
        getSnippet: (env) => {
          const base = env.BASE_EMAIL || 'your@gmail.com';
          const derive = (actor) => base.replace('@', `+${actor}@`);
          return JSON.stringify([
            { identifier: derive('jane'), email: derive('jane'), displayName: 'Jane', verifiedEmail: true },
            { identifier: derive('bill'), email: derive('bill'), displayName: 'Bill', verifiedEmail: true },
            { identifier: derive('beth'), email: derive('beth'), displayName: 'Beth', verifiedEmail: true },
          ], null, 2);
        },
      },
      {
        id: 'step3',
        type: 'gate',
        title: 'Verify Jane, Bill, and Beth are imported',
        description: 'Backend confirms all three accounts exist in Descope.',
        endpoint: '/api/verify/m2-import',
        getBody: () => ({}),
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Spot-check accounts in Descope Console',
        description: 'Confirm Jane, Bill, and Beth appear in User Management as Active with no authentication method configured yet.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M3: {
    title: 'The Password',
    article: 'AFASA Article 5',
    narrative: 'Activate password-based login as an interim measure while passwordless infrastructure is prepared.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Find the password login flow template',
        description: 'In Descope Console → Flows, browse the template library and find "Sign up or in - passwords". Review the flow structure — this is the legacy authentication path.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'input',
        title: 'Save the Flow ID',
        description: 'Copy the Flow ID from Descope and paste it below. This activates the Descope login widget on the /login page.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-in',
        label: 'Flow ID',
      },
      {
        id: 'step3',
        type: 'restart',
        title: 'Restart the Vite dev server',
        description: 'Stop the Vite client (Ctrl+C in terminal 2) and run npm run dev again. VITE_ variables require a restart to take effect.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step4',
        type: 'gate',
        title: 'Verify flow exists in Descope',
        description: 'Backend confirms the flow ID is valid and accessible in your project.',
        endpoint: '/api/verify/flow-exists',
        getBody: (ctx) => ({ flowId: ctx.envValues?.VITE_FLOW_ID }),
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Sign in as Joel and experience the password flow',
        description: 'Go to /login and sign in as Joel (BASE_EMAIL+joel@). Observe the password-based authentication experience — this is the legacy UX we will modernise.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Check the Audit Log in Descope Console',
        description: 'In Descope Console → Audit Logs, find Joel\'s sign-in event. This is your real-time compliance audit trail — AFASA Article 6 in action.',
        buttonLabel: 'Done',
      },
    ],
  },

  M4: {
    title: 'Go Passwordless',
    article: 'AFASA Article 5',
    narrative: 'Migrate Joel\'s legacy account to phishing-resistant passkey authentication per AFASA Article 5.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Find the passkey migration flow template',
        description: 'In Descope Console → Flows → Templates, locate "migrate-users-from-passwords-to-passkeys". Review the A/B routing structure — it handles both new passkey enrollment and returning passkey users.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'input',
        title: 'Save the Flow ID',
        description: 'Copy the migration flow ID and paste below. This overwrites VITE_FLOW_ID from M3.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'migrate-users-from-passwords-to-passkeys',
        label: 'Flow ID',
      },
      {
        id: 'step3',
        type: 'restart',
        title: 'Restart the Vite dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step4',
        type: 'gate',
        title: 'Verify migration flow exists',
        description: 'Backend confirms the migration flow ID is accessible in your project.',
        endpoint: '/api/verify/flow-exists',
        getBody: (ctx) => ({ flowId: ctx.envValues?.VITE_FLOW_ID }),
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Sign in as Joel and enroll a passkey',
        description: 'Go to /login and sign in as Joel. The migration flow will prompt you to enroll a passkey. Complete the WebAuthn enrollment in your browser.',
        buttonLabel: 'Passkey Enrolled',
      },
      {
        id: 'step6',
        type: 'gate',
        title: 'Verify Joel has a passkey enrolled',
        description: 'Backend checks Joel\'s Descope account for a registered WebAuthn credential.',
        endpoint: '/api/verify/passkey-enrolled',
        getBody: () => ({ actor: 'joel' }),
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Sign out and sign back in via passkey',
        description: 'Sign out of Joel\'s session, then return to /login. The flow should authenticate via passkey — no password prompt this time.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Confirm passkey in Descope Console',
        description: 'In Descope → User Management → find Joel → confirm the passkey credential appears under his account.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M5: {
    title: 'New Arrivals',
    article: 'AFASA Article 5',
    narrative: 'Prove that a brand-new banking customer can self-register and authenticate without ever setting a password — magic link or passkey, zero friction.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Review the pre-imported customers in Descope',
        description: 'In Descope Console → User Management, confirm Jane, Bill, and Beth exist as Active accounts with no authentication credentials. This demonstrates AFASA Article 4 bulk identity import — accounts exist but cannot log in yet. The next steps prove the self-service onboarding path for net-new customers.',
        buttonLabel: 'Noted',
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Find the passwordless sign-up flow template',
        description: 'In Descope Console → Flows → Templates, locate "Sign up or in – passkeys or magic link". This flow handles a brand-new customer arriving at the portal — they sign up via magic link, then are prompted to enroll a passkey for future frictionless access.',
        buttonLabel: 'Done',
      },
      {
        id: 'step3',
        type: 'input',
        title: 'Save the Flow ID',
        description: 'Copy the Flow ID and paste below. This replaces the M4 migration flow — new customers now land on this passwordless path.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-up-or-in-passkeys-magic-link',
        label: 'Flow ID',
      },
      {
        id: 'step4',
        type: 'restart',
        title: 'Restart the Vite dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Sign up as a brand-new customer via Magic Link',
        description: 'Go to /login and enter a new email address (e.g. BASE_EMAIL+newcustomer@). This account does not exist in Descope yet. The flow will send a magic link — check the inbox, click it, and complete sign-up. This simulates a net-new banking customer self-registering on the public portal.',
        buttonLabel: 'Signed Up',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Enroll a passkey when prompted',
        description: 'After the magic link is verified, the flow should prompt "Configure Passkeys?" — click "Add passkeys" and complete the WebAuthn enrollment. The customer now has passwordless access for all future logins.',
        buttonLabel: 'Passkey Enrolled',
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Sign out and sign back in via passkey',
        description: 'Sign out, return to /login, and click "Sign in with Passkeys". The new customer authenticates instantly — no magic link, no password. This is the AFASA Article 5 passwordless experience.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Confirm new customer in Descope Console',
        description: 'In Descope → User Management, find the new customer account and confirm the passkey credential appears. AFASA Article 5 self-service onboarding is verified.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M6: {
    title: 'Breach Check',
    article: 'AFASA Article 6',
    narrative: 'Enforce AFASA-compliant password policy and activate breach credential detection on new sign-ups.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Set password policy in Descope Console',
        description: 'Go to Descope → Auth Methods → Passwords → Password Policy. Set: minimum length 10, require uppercase letter, require number, require special character. Save the policy.',
        buttonLabel: 'Policy Saved',
      },
      {
        id: 'step2',
        type: 'gate',
        title: 'Verify password policy is AFASA compliant',
        description: 'Backend fetches your Descope password policy and confirms all four requirements are active.',
        endpoint: '/api/verify/password-policy',
        getBody: () => ({}),
      },
      {
        id: 'step3',
        type: 'trust',
        title: 'Create a new flow from the passwords template',
        description: 'In Descope Console → Flows, create a new flow from "Sign up or in - passwords". This will be your HIBP-enabled sign-up path. Save it.',
        buttonLabel: 'Done',
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Add the HIBP connector to the sign-up path',
        description: 'In the new flow\'s sign-up branch, add a HIBP (Have I Been Pwned) connector step. Configure it to block compromised passwords. Save and publish the flow.',
        buttonLabel: 'Done',
      },
      {
        id: 'step5',
        type: 'input',
        title: 'Save the new Flow ID',
        description: 'Copy the Flow ID of the HIBP-enabled flow and paste below. This replaces VITE_FLOW_ID.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-in-hibp',
        label: 'Flow ID',
      },
      {
        id: 'step6',
        type: 'restart',
        title: 'Restart the Vite dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Test: Sign up as Chris with "Password123!"',
        description: 'Go to /login and sign up as BASE_EMAIL+chris@ using "Password123!" — a known breached credential. Observe that HIBP blocks the registration.',
        buttonLabel: 'Blocked ✓',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Test: Sign up as Mike with a strong clean password',
        description: 'Sign up as BASE_EMAIL+mike@ with a strong password not in HIBP (e.g. "Clearbank@2024!"). Observe successful sign-up.',
        buttonLabel: 'Mike Created ✓',
      },
      {
        id: 'step9',
        type: 'gate',
        title: 'Verify Mike was onboarded successfully',
        description: 'Backend confirms BASE_EMAIL+mike@ exists in Descope with an active status.',
        endpoint: '/api/verify/user-exists',
        getBody: () => ({ actor: 'mike' }),
      },
      {
        id: 'step10',
        type: 'trust',
        title: 'Confirm Mike in Descope Console',
        description: 'In Descope → User Management, find Mike\'s account and confirm it is active.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M7: {
    title: 'The Final Flow',
    article: 'AFASA Article 5',
    narrative: 'Consolidate all authentication paths into one unified flow covering every customer segment — legacy customers, new customers, and new sign-ups.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Review the sign-up-or-in-bank flow',
        description: 'In Descope Console → Flows, find the "sign-up-or-in-bank" flow template. Open and review its structure — it handles password login, passkey sign-in, and new customer sign-up in a single entry point. Click Done when reviewed.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'input',
        title: 'Import the flow and paste its Flow ID',
        description: 'Import (or clone) the "sign-up-or-in-bank" flow in Descope. Copy its Flow ID and paste it below. This becomes the permanent VITE_FLOW_ID — M9 will restore this same ID.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-up-or-in-bank',
        label: 'Unified Flow ID',
      },
      {
        id: 'step3',
        type: 'restart',
        title: 'Restart the dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again. VITE_ variables require a full restart.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step4',
        type: 'gate',
        title: 'Verify unified flow exists in Descope',
        description: 'Backend confirms the unified flow ID is valid and accessible in your Descope project.',
        endpoint: '/api/verify/flow-exists',
        getBody: (ctx) => ({ flowId: ctx.envValues?.VITE_FLOW_ID }),
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Smoke test: Sign in as Joel (passkey path)',
        description: 'Go to /login and sign in as Joel. The unified flow should route Joel through his passkey credential. Confirm dashboard access.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Smoke test: Sign in as Jane (passwordless path)',
        description: 'Sign out, then sign in as Jane. The unified flow routes Jane through the magic link / passkey path. Confirm dashboard access.',
        buttonLabel: 'Done',
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Smoke test: Sign up as a new test user',
        description: 'Sign out, then sign up as a brand-new test account (e.g. BASE_EMAIL+test7@). The unified flow handles new sign-ups too — no separate flow needed.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Console spot-check all three user types',
        description: 'In Descope Console → User Management, confirm Joel (passkey), Jane (passwordless), and your test user all appear with correct auth methods. AFASA Article 5 is fully covered.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M8: {
    title: 'Geo Block',
    article: 'AFASA Article 9',
    narrative: 'Implement geographic access restrictions per AFASA Article 9 — block sign-ins from embargoed jurisdictions.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Find the geo-block flow template in Descope',
        description: 'In Descope Console → Flows, locate the template "Sign up or in - Deny access from US embargoed countries". Open and review it — observe how the geo condition blocks specific country codes.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'input',
        title: 'Add PH to the embargoed list, save, and paste the Flow ID',
        description: 'Edit the flow: add PH (Philippines) to the blocked country list as a test. Save and publish the flow. Copy the Flow ID and paste it below — backend will write it to VITE_FLOW_ID.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-up-or-in-geo-block',
        label: 'Geo-Block Flow ID',
      },
      {
        id: 'step3',
        type: 'restart',
        title: 'Restart the dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step4',
        type: 'gate',
        title: 'Verify geo-block flow exists in Descope',
        description: 'Backend confirms the geo-block flow ID is valid and accessible in your Descope project.',
        endpoint: '/api/verify/flow-exists',
        getBody: (ctx) => ({ flowId: ctx.envValues?.VITE_FLOW_ID }),
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Observe the 403 Forbidden screen',
        description: 'Go to /login and attempt to sign in. Because PH is in the block list, you should see a 403 Forbidden / access denied screen from the flow.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Remove PH — add RU and CN to the block list',
        description: 'Back in Descope Flow Builder, edit the geo-block flow: remove PH from the blocked list, add RU and CN. Save and publish. No restart needed — same flow ID.',
        buttonLabel: 'Done',
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Confirm sign-in now succeeds',
        description: 'Go to /login again and sign in. With PH removed, authentication should succeed. AFASA Article 9 geo controls are verified.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Console spot-check the geo rules',
        description: 'In Descope Console, verify the flow shows RU and CN in the blocked list. AFASA Article 9 is now closed.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M9: {
    title: 'Guard the Gate',
    article: 'AFASA Article 7',
    narrative: 'Prove server-side session validation and demonstrate instant session revocation — AFASA Article 7 compliance.',
    steps: [
      {
        id: 'step0',
        type: 'input',
        title: 'Restore the M7 unified Flow ID',
        description: 'Mission 9 uses the M7 baseline flow (without geo-blocking). Paste the M7 unified flow ID below — backend writes it back to VITE_FLOW_ID.',
        envKey: 'VITE_FLOW_ID',
        placeholder: 'sign-up-or-in-bank',
        label: 'M7 Flow ID',
      },
      {
        id: 'step1',
        type: 'restart',
        title: 'Restart the dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Sign in as Joel',
        description: 'Go to /login and sign in as Joel using his passkey. Confirm you land on the dashboard.',
        buttonLabel: 'Done',
      },
      {
        id: 'step3',
        type: 'trust',
        title: 'Click View Account Balance — observe it works',
        description: 'Navigate to /balance. The page makes a server-side session call on every load. Confirm the balance data renders — this is AFASA Article 7 session validation in action.',
        buttonLabel: 'Done',
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Locate the DST session token in Local Storage',
        description: 'Open DevTools → Application → Local Storage → find the key starting with "DST". Copy the full JWT value.',
        buttonLabel: 'Done',
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Decode the token in jwt.io — confirm amr contains webauthn',
        description: 'Paste the token at jwt.io. Read the decoded payload — confirm the amr array contains "webauthn", proving Joel used a passkey.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'gate',
        title: 'Backend validates Joel\'s live session',
        description: 'The wizard sends your current session token to the backend, which calls validateSession() and returns the decoded claims panel here.',
        endpoint: '/api/verify/m9-session',
        getBody: () => ({}),
        showClaims: true,
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Console → Revoke All Sessions for Joel',
        description: 'In Descope Console → User Management → Joel → Sessions → click "Revoke All Sessions". This invalidates the token immediately.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Click View Account Balance again — observe 401. Confirm in Console.',
        description: 'Return to /balance. Joel is now kicked out — the page should return a 401 or redirect to /login. Then in Descope Console confirm Joel has no active sessions.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M10: {
    title: 'High Stakes',
    article: 'AFASA Article 8',
    narrative: 'Add step-up authentication for transfers above ₱50,000 — AFASA Article 8 requires re-verification before high-value operations.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Find the Step-Up Authentication template in Descope',
        description: 'In Descope Console → Flows, locate the Step Up Authentication template. Open and review its structure — it challenges the user mid-session before a sensitive operation.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Edit the step-up flow — add Passkey re-verification',
        description: 'In the step-up flow editor, remove Magic Link and OAuth options. Add Passkey (WebAuthn) as the re-verification method. Save and publish the flow.',
        buttonLabel: 'Done',
      },
      {
        id: 'step3',
        type: 'input',
        title: 'Paste the Step-Up Flow ID',
        description: 'Copy the step-up flow ID from Descope and paste it below. This is stored as VITE_STEPUP_FLOW_ID — it never overwrites VITE_FLOW_ID.',
        envKey: 'VITE_STEPUP_FLOW_ID',
        placeholder: 'step-up-passkey',
        label: 'Step-Up Flow ID',
      },
      {
        id: 'step4',
        type: 'restart',
        title: 'Restart the dev server',
        description: 'Stop Vite (Ctrl+C) and run npm run dev again.',
        buttonLabel: "I've Restarted",
      },
      {
        id: 'step5',
        type: 'gate',
        title: 'Verify step-up flow exists in Descope',
        description: 'Backend reads VITE_STEPUP_FLOW_ID and confirms the flow is accessible in your Descope project.',
        endpoint: '/api/verify/stepup-flow-exists',
        getBody: () => ({}),
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Sign in as Joel',
        description: 'Go to /login and sign in as Joel via passkey. Confirm dashboard access.',
        buttonLabel: 'Done',
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Transfer above ₱50,000 — step-up fires',
        description: 'Go to /transfer and enter an amount above ₱50,000 (e.g. ₱60,000). The Descope step-up widget should appear requiring Joel to re-verify via passkey. Complete the challenge — the transfer proceeds.',
        buttonLabel: 'Done',
      },
      {
        id: 'step8',
        type: 'trust',
        title: 'Transfer below ₱50,000 — step-up does NOT fire',
        description: 'Enter an amount below ₱50,000 (e.g. ₱20,000). The transfer should proceed directly — no step-up challenge. Confirm this threshold behaviour works correctly.',
        buttonLabel: 'Done',
      },
      {
        id: 'step9',
        type: 'trust',
        title: 'Console → Audit Logs — confirm step-up event for Joel',
        description: 'In Descope Console → Audit Logs, find the step-up authentication event triggered by Joel\'s high-value transfer. AFASA Article 8 is now closed.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M11: {
    title: 'Paper Trail',
    article: 'AFASA Articles 6, 10 and 11',
    narrative: 'Stream Descope audit events to Honeycomb over OpenTelemetry. Cloud-to-cloud — no local configuration required. Build a compliance dashboard covering all AFASA audit articles.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Explore all audit events from M1–M10 in Descope',
        description: 'In Descope Console → Audit Logs, browse the full event history from the training. Observe the breadth of events captured: sign-ins, passkey enrollments, step-up challenges, session revocations. Click Done when explored.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Create a Honeycomb account and copy your Ingest API key',
        description: 'Go to honeycomb.io and sign up free. Create a new Environment named "securebank-afasa". In Team Settings → API Keys, generate an Ingest key with write access. Copy it.',
        buttonLabel: 'Done',
      },
      {
        id: 'step3',
        type: 'trust',
        title: 'Add OpenTelemetry connector in Descope',
        description: 'In Descope Console → Connectors → Add → OpenTelemetry. Configure the endpoint (api.honeycomb.io:443) and headers (x-honeycomb-team: <your-key>, x-honeycomb-dataset: securebank-afasa). Save.',
        buttonLabel: 'Done',
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Enable Audit Streaming to the OTEL connector',
        description: 'In Descope Console → Project Settings → Audit → Enable Audit Streaming. Select your OpenTelemetry connector. Save. All future auth events now stream to Honeycomb.',
        buttonLabel: 'Done',
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Sign in as Joel — confirm event arrives in Honeycomb',
        description: 'Go to /login and sign in as Joel. Switch to Honeycomb → Query → your dataset. The sign-in event should appear within 30 seconds.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Run 3 compliance queries in Honeycomb',
        description: 'Build and run the following queries: (1) All events for Joel\'s email, (2) All step-up authentication events, (3) Event count GROUP BY auth method. These cover AFASA Articles 6, 10, and 11.',
        buttonLabel: 'Done',
      },
      {
        id: 'step7',
        type: 'trust',
        title: 'Save all 3 queries to a Board named "AFASA Compliance — SecureBank"',
        description: 'In Honeycomb, save each of your 3 queries and add them to a new Board named "AFASA Compliance — SecureBank". This board is your persistent compliance reporting dashboard.',
        buttonLabel: 'Confirmed',
      },
    ],
  },

  M12: {
    title: 'Red Alert',
    article: 'AFASA Article 11',
    narrative: 'A credential stuffing attack is underway. Detect, lock, investigate in Honeycomb, and recover — closing the AFASA compliance cycle.',
    steps: [
      {
        id: 'step1',
        type: 'trust',
        title: 'Phase 1 — Detect: Configure lockout policy',
        description: 'In Descope Console → Auth Methods → Passwords, set max failed attempts = 3 and lockout duration = 3 minutes. Save. This activates automatic account lockout on repeated failures.',
        buttonLabel: 'Done',
      },
      {
        id: 'step2',
        type: 'trust',
        title: 'Trigger the lockout: Sign in as Mike with wrong passwords 3 times',
        description: 'Go to /login and attempt to sign in as BASE_EMAIL+mike@ with incorrect passwords three times in a row. On the third failure, observe the lockout message.',
        buttonLabel: 'Done',
      },
      {
        id: 'step3',
        type: 'gate',
        title: 'Verify Mike\'s account is locked',
        description: 'Backend loads Mike\'s account via the Management API and confirms his status is locked.',
        endpoint: '/api/verify/m12-locked',
        getBody: () => ({}),
      },
      {
        id: 'step4',
        type: 'trust',
        title: 'Phase 2 — Lock: Revoke all of Mike\'s sessions',
        description: 'In Descope Console → User Management → Mike → Sessions → click "Revoke All Sessions". Any existing session tokens are immediately invalidated.',
        buttonLabel: 'Done',
      },
      {
        id: 'step5',
        type: 'trust',
        title: 'Phase 3 — Investigate: Read the attack timeline in Honeycomb',
        description: 'In Honeycomb, filter events by Mike\'s email address. Read the full attack timeline: the failed attempts, the lockout event, and the session revocation. This is your AFASA Article 11 evidence trail.',
        buttonLabel: 'Done',
      },
      {
        id: 'step6',
        type: 'trust',
        title: 'Phase 4 — Recover: Clear Mike\'s lockout. Incident closed.',
        description: 'In Descope Console → User Management → Mike, clear the lockout (re-enable the account). Mike can now log in again. The incident is documented, contained, and closed. ClearBank is AFASA Certified.',
        buttonLabel: 'Incident Closed — AFASA Certified',
      },
    ],
  },
};
